# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Eventi-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Eventi-iOS
pod 'SwiftyJSON'
pod 'Alamofire'
pod 'IQKeyboardManager'
pod 'Toast-Swift'
pod 'SDWebImage', '~> 5.0'
end
